---
#  - name: If necessary create the .ssh folder and set access permissions
#    local_action: shell mkdir -p ~/.ssh; chmod u=rwx,go= ~/.ssh

  - name: If necessary create the /tmp/{{ env }} folder
    local_action: shell mkdir -p /tmp/{{ env }}

#  - name: Download the SSH private key from AWS S3 to Ansible host
#    local_action: s3 bucket={{ s3_bucket }} region={{ s3_region }} object=common/admin-key-pairs/{{ role }}/ghe-admin-private-key dest=~/.ssh/{{ ghe_admin_key_name }}-private-key.pem mode=get

#  - name: Download the SSH public key from AWS S3 to Ansible host
#    local_action: s3 bucket={{ s3_bucket }} region={{ s3_region }} object=common/admin-key-pairs/{{ role }}/ghe-admin-public-key dest=~/.ssh/{{ ghe_admin_key_name }}-public-key.pub mode=get

#  - name: Set access permissions of the key files
#    local_action: shell chmod u=rw,go= ~/.ssh/{{ ghe_admin_key_name }}-*-key.*

  - name: Download the vault_ghe_pass.txt file from AWS S3 to Ansible host
    local_action: s3 bucket={{ s3_bucket }} region={{ s3_region }} object=deployment/ansible/{{ role }}/common/.vault_ghe_pass.txt dest=/tmp/.vault_ghe_pass.txt mode=get

  - name: Download the .aws_credential.txt file from AWS S3 to Ansible host
    local_action: s3 bucket={{ s3_bucket }} region={{ s3_region }} object=deployment/aws/common/.aws_credential.txt dest=/tmp/.aws_credential.txt mode=get

  - name: Download the GHE license file from S3 bucket
    s3: bucket={{ s3_bucket }} region={{ s3_region }} object=deployment/ghe/common/enterprise.ghl dest=/tmp/{{ env }}/enterprise.ghl mode=get

  - name: Download the GHE settings file from S3
    s3: bucket={{ s3_bucket }} region={{ s3_region }} object=deployment/ansible/{{ role }}/{{ env }}/ghe-settings.json dest=/tmp/{{ env }}/ghe-settings.json mode=get

  - name: Download the auto-testing key file from S3
    s3: bucket={{ s3_bucket }} region={{ s3_region }} object=common/test-key/.vault_test_key.txt dest=/tmp/.vault_test_key.txt mode=get
